# frontend/Dockerfile

# Etapa 1: Construcción (Build)
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: Producción (Servir con Nginx)
FROM nginx:stable-alpine as production-stage
# Copia los archivos compilados de Vue a la carpeta pública de Nginx
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]