name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main # Cambia esto a "master" si tu rama principal se llama así

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código (Checkout)
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen del Backend (Laravel)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          # Cambia "simexweb-backend" por el nombre de repositorio que prefieras
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simexweb-backend:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código (Checkout)
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen del Frontend (Vue)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          # Cambia "simexweb-frontend" por el nombre de repositorio que prefieras
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simexweb-frontend:latest